CREATE DATABASE SLTQuizDB;
GO

USE SLTQuizDB;
GO

CREATE TABLE Scores (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(200) NOT NULL,
    Tp NVARCHAR(100) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    Score INT NOT NULL,
    TotalQuestions INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE QuizSettings (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Category NVARCHAR(100) NOT NULL UNIQUE,
    QuestionCount INT NOT NULL DEFAULT 5
);
GO
