USE phvtech_main;
GO

CREATE TABLE dbo.slt_score (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(200) NOT NULL,
    Tp NVARCHAR(100) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    Score INT NOT NULL,
    TotalQuestions INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);
GO
